// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Lingua contributors

import { randomUUID } from "node:crypto";
import cors from "@fastify/cors";
import helmet from "@fastify/helmet";
import jwt from "@fastify/jwt";
import cookie from "@fastify/cookie";
import Fastify, { type FastifyInstance } from "fastify";
import { getCorsOrigins, getServerEnv } from "@lingua/config";
import { createProblem, sendProblem } from "./problem";
import { registerCatalogRoutes } from "./routes/catalog";
import { registerAuthRoutes } from "./routes/auth";
import { registerLearnerRoutes } from "./routes/learner";

export type BuildAppOptions = {
  /** Tests pass `false` to keep output clean. */
  logger?: boolean;
};

/**
 * Build the HTTP server.
 *
 * Route handlers registered here orchestrate only. Domain rules live in
 * packages/core and are imported, never reimplemented: see the dependency rules
 * in docs/architecture/01-system-architecture.md.
 */
export async function buildApp(options: BuildAppOptions = {}): Promise<FastifyInstance> {
  const env = getServerEnv();

  const app = Fastify({
    logger: options.logger ?? { level: env.LOG_LEVEL },
    // Correlation ids are always generated by the server. An incoming
    // X-Request-Id is deliberately NOT trusted: letting a caller choose values
    // that end up in our logs is a log-injection vector.
    genReqId: () => randomUUID(),
    trustProxy: true,
  });

  await app.register(helmet);
  await app.register(cors, {
    origin: getCorsOrigins(env),
    credentials: true,
  });

  // JWT support for auth tokens
  await app.register(jwt, {
    secret: env.AUTH_SECRET ?? "dev-secret-change-in-production-min-32-chars!!",
    sign: { algorithm: "HS256" },
  });

  // Cookie support for refresh tokens
  await app.register(cookie);

  // Echo the correlation id so a user-reported failure can be traced to logs.
  app.addHook("onSend", async (request, reply) => {
    reply.header("x-request-id", request.id);
  });

  app.get("/health", async () => ({
    status: "ok",
    uptime_seconds: Math.round(process.uptime()),
  }));

  await registerCatalogRoutes(app);
  await registerAuthRoutes(app);
  await registerLearnerRoutes(app);

  app.setNotFoundHandler((request, reply) => {
    sendProblem(
      reply,
      createProblem({
        code: "not_found",
        detail: `No route matches ${request.method} ${request.url}.`,
        instance: request.url,
        requestId: request.id,
      }),
    );
  });

  app.setErrorHandler((error, request, reply) => {
    const issues = readValidationIssues(error);
    if (issues) {
      sendProblem(
        reply,
        createProblem({
          code: "validation_failed",
          detail: "Request validation failed.",
          instance: request.url,
          requestId: request.id,
          errors: issues.map((issue) => ({
            path: issue.instancePath.length > 0 ? issue.instancePath : "(root)",
            message: issue.message ?? "Invalid value",
          })),
        }),
      );
      return;
    }

    request.log.error({ err: error }, "unhandled request error");
    sendProblem(
      reply,
      createProblem({
        code: "internal",
        detail: "An unexpected error occurred. The request id can be used to trace this.",
        instance: request.url,
        requestId: request.id,
      }),
    );
  });

  return app;
}

type ValidationIssue = { instancePath: string; message?: string };

/**
 * Extract schema validation failures from a thrown value.
 *
 * Fastify types the error handler argument as `unknown`, which is correct: a
 * handler can receive anything. Narrow it here instead of casting, so a thrown
 * string or `null` cannot crash the error path itself.
 */
function readValidationIssues(error: unknown): ValidationIssue[] | undefined {
  if (typeof error !== "object" || error === null) {
    return undefined;
  }

  const candidate = (error as { validation?: unknown }).validation;
  if (!Array.isArray(candidate)) {
    return undefined;
  }

  return candidate.map((issue) => {
    const record =
      typeof issue === "object" && issue !== null ? (issue as Record<string, unknown>) : {};
    return {
      instancePath: typeof record.instancePath === "string" ? record.instancePath : "(root)",
      message: typeof record.message === "string" ? record.message : undefined,
    };
  });
}
